version: '3.7'

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwd
    ports:
      - 5432:5432
