---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ydr-user-service-config
data:
  POSTGRES_USERNAME: "{{ .Values.postgresUsername }}" 
  POSTGRES_PASSWORD: "{{ .Values.postgresPassword }}" 
  POSTGRES_HOST: "{{ .Values.postgresHost }}" 
  POSTGRES_PORT: "{{ .Values.postgresPort }}" 
  POSTGRES_DATABASE: "{{ .Values.postgresDatabase }}"
  APP_PORT: "{{ .Values.appPort }}"

